const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  getUsers: () => ipcRenderer.invoke('get-users'),
  addUser: (user) => ipcRenderer.invoke('add-user', user),
  getQuizzes: () => ipcRenderer.invoke('get-quizzes'),
  addQuiz: (quiz) => ipcRenderer.invoke('add-quiz', quiz),
  getResults: () => ipcRenderer.invoke('get-results'),
  addResult: (result) => ipcRenderer.invoke('add-result', result),
  getInstructors: () => ipcRenderer.invoke('get-instructors'),
  addInstructor: (instructor) => ipcRenderer.invoke('add-instructor', instructor),
  getPackages: () => ipcRenderer.invoke('get-packages'),
  addPackage: (pkg) => ipcRenderer.invoke('add-package', pkg),
  getSpecializations: () => ipcRenderer.invoke('get-specializations'),
  addSpecialization: (specialization) => ipcRenderer.invoke('add-specialization', specialization),
  getCertifications: () => ipcRenderer.invoke('get-certifications'),
  addCertification: (certification) => ipcRenderer.invoke('add-certification', certification),
  updateUser: (user) => ipcRenderer.invoke('update-user', user),
  updateQuiz: (quiz) => ipcRenderer.invoke('update-quiz', quiz),
  updateInstructor: (instructor) => ipcRenderer.invoke('update-instructor', instructor),
  updateSpecialization: (specialization) => ipcRenderer.invoke('update-specialization', specialization),
  updateCertification: (certification) => ipcRenderer.invoke('update-certification', certification),
  deleteUser: (userId) => ipcRenderer.invoke('delete-user', userId),
  deleteQuiz: (quizId) => ipcRenderer.invoke('delete-quiz', quizId),
  deleteInstructor: (instructorId) => ipcRenderer.invoke('delete-instructor', instructorId),
  fetchExam: (token) => ipcRenderer.invoke('fetch-exam', token),
  fetchExamDuration: () => ipcRenderer.invoke('fetch-exam-duration'),
  setExamTimeframe: (time) => ipcRenderer.invoke('set-exam-timeframe', time),
  sync: () => ipcRenderer.invoke('sync'),
  login: (credentials) => ipcRenderer.invoke('login', credentials),
});
